### Accepted
POST http://localhost:8080/api/raises
Content-Type: application/json

{
  "currentSalary": 3000,
  "proposedRaiseDate": "2022-05-10",
  "proposedSalary": 3299.99,
  "previousRaises": [
    { "id": "30.DEC.2020-3000", "date": "2020-12-30", "acceptedSalary": 3000 }
  ]
}

### Null salary
POST http://localhost:8080/api/raises
Content-Type: application/json

{
  "currentSalary": null,
  "proposedRaiseDate": "2022-05-10",
  "proposedSalary": 3299.99,
  "previousRaises": [
    { "id": "30.DEC.2020-3000", "date": "2020-12-30", "acceptedSalary": 3000 }
  ]
}

### Too soon
POST http://localhost:8080/api/raises
Content-Type: application/json

{
  "currentSalary": 3000,
  "proposedRaiseDate": "2022-05-10",
  "proposedSalary": 3299.99,
  "previousRaises": [
    { "id": "30.DEC.2020-3000", "date": "2020-12-30", "acceptedSalary": 3000 }
  ]
}

### Too late
POST http://localhost:8080/api/raises
Content-Type: application/json

{
  "currentSalary": 3000,
  "proposedRaiseDate": "2022-05-10",
  "proposedSalary": 3299.99,
  "previousRaises": [
    { "id": "30.DEC.2020-3000", "date": "2020-12-30", "acceptedSalary": 3000 }
  ]
}

### Too big
POST http://localhost:8080/api/raises
Content-Type: application/json

{
  "currentSalary": 3000,
  "proposedRaiseDate": "2022-05-10",
  "proposedSalary": 4000,
  "previousRaises": [
    { "id": "30.DEC.2020-3000", "date": "2020-12-30", "acceptedSalary": 3000 }
  ]
}

### Too many raises
POST http://localhost:8080/api/raises
Content-Type: application/json

{
  "currentSalary": 15000,
  "proposedRaiseDate": "2022-05-10",
  "proposedSalary": 16000,
  "previousRaises": [
    { "id": "30.JUN.2020-15000", "date": "2021-06-30", "acceptedSalary": 15000 },
    { "id": "30.MAY.2020-14000", "date": "2020-05-30", "acceptedSalary": 14000 },
    { "id": "30.APR.2020-13000", "date": "2020-04-30", "acceptedSalary": 13000 },
    { "id": "30.MAR.2020-12000", "date": "2020-03-30", "acceptedSalary": 12000 }
  ]
}

### Incorrect id format
POST http://localhost:8080/api/raises
Content-Type: application/json

{
  "currentSalary": 3000,
  "proposedRaiseDate": "2022-05-10",
  "proposedSalary": 3299.99,
  "previousRaises": [
    { "id": "123", "date": "2020-12-30", "acceptedSalary": 3000 }
  ]
}